apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskapp
spec:
  replicas: 1
  strategy:
    type: Recreate # verhindert 2 gleichzeitige Writer auf dasselbe Volume
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata # verhindert Probleme mit lost+found im Root des Volumes
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "tasksuser"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: taskapp
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
